# Generated by Django 2.2.4 on 2020-10-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerly_app', '0002_auto_20201021_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
