# Generated by Django 2.2.4 on 2021-01-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readerly_app', '0003_auto_20201022_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
